{{- if and .Values.secrets.create .Values.secrets.apiTokenLiteral }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.apiTokenSecretName }}
type: Opaque
data:
  SOMA_API_TOKEN: {{ .Values.secrets.apiTokenLiteral | b64enc | quote }}
{{- end }}

{{- if and .Values.secrets.create .Values.secrets.postgresPasswordLiteral }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgresPasswordSecretName }}
type: Opaque
data:
  SOMA_POSTGRES_PASSWORD: {{ .Values.secrets.postgresPasswordLiteral | b64enc | quote }}
{{- end }}
