apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --profile core -o infra/k8s/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
    - name: "10101"
      port: 10101
      targetPort: 10101
  selector:
    io.kompose.service: api
