apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --profile core -o infra/k8s/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: etcd
  name: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: etcd
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --profile core -o infra/k8s/
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: etcd
    spec:
      containers:
        - args:
            - etcd
            - --advertise-client-urls=http://127.0.0.1:2379
            - --listen-client-urls=http://0.0.0.0:2379
            - --data-dir=/etcd
            - --auto-compaction-mode=periodic
            - --auto-compaction-retention=1h
            - --quota-backend-bytes=8589934592
            - --snapshot-count=10000
            - --max-txn-ops=10000
            - --max-request-bytes=10485760
          image: quay.io/coreos/etcd:v3.5.5
          livenessProbe:
            exec:
              command:
                - etcdctl
                - endpoint
                - health
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 20
          name: somafractalmemory-etcd
          resources:
            limits:
              memory: "1073741824"
            requests:
              memory: "536870912"
          volumeMounts:
            - mountPath: /etcd
              name: etcddata
      restartPolicy: Always
      volumes:
        - name: etcddata
          persistentVolumeClaim:
            claimName: etcddata
