apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --profile core -o infra/k8s/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: milvus
  name: milvus
spec:
  ports:
    - name: "10530"
      port: 10530
      targetPort: 19530
    - name: "10531"
      port: 10531
      targetPort: 9091
  selector:
    io.kompose.service: milvus
