apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --profile core -o infra/k8s/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: milvus
  name: milvus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: milvus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --profile core -o infra/k8s/
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: milvus
    spec:
      containers:
        - args:
            - milvus
            - run
            - standalone
          env:
            - name: ETCD_ENDPOINTS
              value: etcd:2379
            - name: MINIO_ADDRESS
              value: minio:9000
          image: milvusdb/milvus:v2.3.3
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:9091/healthz || exit 1
            failureThreshold: 5
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 10
          name: somafractalmemory-milvus
          ports:
            - containerPort: 19530
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
          resources:
            limits:
              memory: "8589934592"
            requests:
              memory: "4294967296"
          volumeMounts:
            - mountPath: /var/lib/milvus
              name: milvusdata
      restartPolicy: Always
      volumes:
        - name: milvusdata
          persistentVolumeClaim:
            claimName: milvusdata
