apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --profile core -o infra/k8s/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --profile core -o infra/k8s/
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: minio
    spec:
      containers:
        - args:
            - minio
            - server
            - /minio_data
            - --console-address
            - :9001
          env:
            - name: MINIO_ACCESS_KEY
              value: minioadmin
            - name: MINIO_SECRET_KEY
              value: minioadmin
          image: minio/minio:RELEASE.2023-03-20T20-16-18Z
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:9000/minio/health/live
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 20
          name: somafractalmemory-minio
          resources:
            limits:
              memory: "1073741824"
            requests:
              memory: "536870912"
          volumeMounts:
            - mountPath: /minio_data
              name: miniodata
      restartPolicy: Always
      volumes:
        - name: miniodata
          persistentVolumeClaim:
            claimName: miniodata
