apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --profile core -o infra/k8s/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
    - name: "10379"
      port: 10379
      targetPort: 6379
  selector:
    io.kompose.service: redis
