# values-local-dev.yaml
# Overrides for local development.

replicaCount: 1

service:
  port: 9595
  targetPort: 9595

postgres:
  replicaCount: 1
  persistence:
    enabled: false
  secrets:
    apiToken: "devtoken"
    postgresPassword: "soma"

redis:
  replicaCount: 1
  persistence:
    enabled: false

qdrant:
  replicaCount: 1
  persistence:
    enabled: false
